title: "GMA-IRE Newsletter"
name: "GMA-IRE Newsletter"
description: "Aggiornamenti mensili su opportunità, eventi, e ricerca"
url: "https://edoardoidaPhd.github.io/GMA-IRE-newsletter"
baseurl: "/newsletter" # se il repo NON è <username>.github.io
theme: minimal-mistakes-jekyll

# impostazioni newsletter
paginate: 5
paginate_path: "/page:num/"

# autore
#author:
#  name   : "Edoardo Ida'"
#  avatar : "..."
#  bio    : "Ricercatore, newsletter editor"
#  location : "Italia"
#  links:
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/username"

# plugins (obbligatori su GH Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
